### ISSUE TITLE
Tasks 

### ISSUE THREAD

**Issue by deekshibellare** [deekshibellare/Tweelight#1]
## Phase 1
- [ ] Implement Side drawer
- [ ] Integrate Twitter API using Social class
- [ ] Implement Network Class
- [ ] Create model 
- [ ] Implement Basic navigation with side panel and home
- [ ] Implement log in page
- [ ] Implement side panel with following options
     * Profile Image
     * Cover Image
     * Profile 
     * Timeline 
     * Settings
     * Analytics
- [ ] Implement timeline
- [ ] Implement Profile - followes, follow, tweets
- [ ] User navigation

## Phase 2
- [ ] Tweet
- [ ] Retweet
- [ ] Favorite
- [ ] Messages 

## Phase 3:
- [ ] Detailed analytics
- [ ] Search
